# Generated by Django 4.1.4 on 2023-04-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Projects',
        ),
    ]
